name: ci

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@REPLACE_WITH_FULL_COMMIT_SHA
      - uses: actions/setup-go@REPLACE_WITH_FULL_COMMIT_SHA
        with:
          go-version-file: go.mod
      - name: Check
        run: make check
